import type { Project } from "@/types";

/* ─────────────────────────────────────────────
   Portfolio Projects — 57 international projects
   across 10 categories
   ───────────────────────────────────────────── */

export const PORTFOLIO_CATEGORIES = [
  "All",
  "E-Commerce",
  "3D & WebGL",
  "SaaS & Technology",
  "Corporate & Business",
  "Tourism & Hospitality",
  "Healthcare & Wellness",
  "Real Estate",
  "Fashion & Luxury",
  "Food & Restaurant",
  "Creative & Portfolio",
] as const;

export type PortfolioCategory = (typeof PORTFOLIO_CATEGORIES)[number];

export const PORTFOLIO_PROJECTS: Project[] = [
  /* ═══════════════════════════════════════
     E-COMMERCE  (8 projects)
     ═══════════════════════════════════════ */
  {
    id: "ec-1",
    slug: "velour-beauty",
    title: "Velour Beauty",
    client: "Velour Cosmetics",
    year: 2025,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/velour-beauty.webp",
    tags: ["Shopify", "Next.js", "GSAP", "Stripe"],
    featured: false,
    description:
      "A luxury beauty brand e-commerce experience with immersive product showcases, 3D lipstick configurator, and AR try-on integration.",
    accentColor: "#d4528a",
  },
  {
    id: "ec-2",
    slug: "nordik-outdoor",
    title: "Nordik Outdoor",
    client: "Nordik Gear Co.",
    year: 2025,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/nordik-outdoor.webp",
    tags: ["Next.js", "Headless CMS", "Three.js", "Stripe"],
    featured: false,
    description:
      "Scandinavian outdoor gear shop with dynamic product filtering, 360° product views, and AI-powered size recommendations.",
    accentColor: "#2d6a4f",
  },
  {
    id: "ec-3",
    slug: "luminary-watches",
    title: "Luminary Watches",
    client: "Luminary Timepieces",
    year: 2025,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/luminary-watches.webp",
    tags: ["React", "WebGL", "GSAP", "Shopify"],
    featured: false,
    description:
      "Swiss luxury watch e-commerce with WebGL-powered 3D watch configurator, engraving preview, and concierge booking system.",
    accentColor: "#c9a84c",
  },
  {
    id: "ec-4",
    slug: "botanica-market",
    title: "Botanica Market",
    client: "Botanica Fresh",
    year: 2026,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/botanica-market.webp",
    tags: ["Next.js", "Supabase", "Stripe", "PWA"],
    featured: false,
    description:
      "Farm-to-table organic marketplace with real-time inventory, subscription boxes, and locality-based delivery scheduling.",
    accentColor: "#52b788",
  },
  {
    id: "ec-5",
    slug: "revolta-motors",
    title: "Revolta Motors",
    client: "Revolta EV",
    year: 2025,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/revolta-motors.webp",
    tags: ["Three.js", "Next.js", "TypeScript", "Stripe"],
    featured: false,
    description:
      "Electric vehicle configurator with real-time 3D customization, range calculator, financing options, and test drive booking.",
    accentColor: "#4361ee",
  },
  {
    id: "ec-6",
    slug: "aether-audio",
    title: "Aether Audio",
    client: "Aether Sound Labs",
    year: 2025,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/aether-audio.webp",
    tags: ["React", "Web Audio API", "GSAP", "Shopify"],
    featured: false,
    description:
      "Premium headphone store with real-time audio comparison tool, 3D product exploration, and personalized sound profile matching.",
    accentColor: "#7b2cbf",
  },
  {
    id: "ec-7",
    slug: "casa-ceramica",
    title: "Casa Ceramica",
    client: "Casa Artisans",
    year: 2026,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/casa-ceramica.webp",
    tags: ["Next.js", "Sanity CMS", "Stripe", "GSAP"],
    featured: false,
    description:
      "Handcrafted ceramics marketplace with artisan stories, kiln-to-door tracking, and an interactive glaze color picker.",
    accentColor: "#e07a5f",
  },
  {
    id: "ec-8",
    slug: "apex-supplements",
    title: "Apex Nutrition",
    client: "Apex Performance",
    year: 2025,
    category: "E-Commerce",
    thumbnail: "/images/projects/portfolio/apex-supplements.webp",
    tags: ["Next.js", "Shopify", "TypeScript", "Tailwind"],
    featured: false,
    description:
      "Sports nutrition e-commerce with AI-driven supplement stacks, macro calculators, and subscription management dashboard.",
    accentColor: "#f77f00",
  },

  /* ═══════════════════════════════════════
     3D & WebGL  (6 projects)
     ═══════════════════════════════════════ */
  {
    id: "3d-1",
    slug: "stellar-space",
    title: "Stellar Space",
    client: "Stellar Aerospace",
    year: 2025,
    category: "3D & WebGL",
    thumbnail: "/images/projects/portfolio/stellar-space.webp",
    tags: ["Three.js", "R3F", "GLSL", "Next.js"],
    featured: false,
    description:
      "An interactive space exploration experience showcasing satellite constellations with real-time orbital tracking and WebGL-rendered Earth.",
    accentColor: "#1d3557",
  },
  {
    id: "3d-2",
    slug: "vertigo-studios",
    title: "Vertigo Studios",
    client: "Vertigo Creative",
    year: 2026,
    category: "3D & WebGL",
    thumbnail: "/images/projects/portfolio/vertigo-studios.webp",
    tags: ["Three.js", "GSAP", "Blender", "WebGL"],
    featured: false,
    description:
      "A motion design studio portfolio with full-screen 3D scene transitions, particle morphing between projects, and GPU-accelerated video playback.",
    accentColor: "#e63946",
  },
  {
    id: "3d-3",
    slug: "atlas-geography",
    title: "Atlas Geo",
    client: "Atlas Geographic Institute",
    year: 2025,
    category: "3D & WebGL",
    thumbnail: "/images/projects/portfolio/atlas-geography.webp",
    tags: ["Three.js", "Mapbox GL", "D3.js", "React"],
    featured: false,
    description:
      "Interactive 3D globe data visualization platform for geographic research — terrain elevation, climate layers, and population density heatmaps.",
    accentColor: "#0077b6",
  },
  {
    id: "3d-4",
    slug: "neuron-lab",
    title: "Neuron Lab",
    client: "Neuron AI Research",
    year: 2026,
    category: "3D & WebGL",
    thumbnail: "/images/projects/portfolio/neuron-lab.webp",
    tags: ["R3F", "GLSL Shaders", "TypeScript", "Next.js"],
    featured: false,
    description:
      "AI research lab website featuring a real-time neural network visualization that responds to user input, built with custom GLSL shaders.",
    accentColor: "#9b5de5",
  },
  {
    id: "3d-5",
    slug: "oceanic-dive",
    title: "Oceanic Dive",
    client: "Oceanic Expeditions",
    year: 2025,
    category: "3D & WebGL",
    thumbnail: "/images/projects/portfolio/oceanic-dive.webp",
    tags: ["Three.js", "WebGL", "GSAP", "Blender"],
    featured: false,
    description:
      "Deep sea exploration experience with underwater 3D environments, bioluminescent creature animations, and scroll-driven depth navigation.",
    accentColor: "#023e8a",
  },
  {
    id: "3d-6",
    slug: "prism-architecture",
    title: "Prism Arch",
    client: "Prism Architecture",
    year: 2026,
    category: "3D & WebGL",
    thumbnail: "/images/projects/portfolio/prism-architecture.webp",
    tags: ["Three.js", "Blender", "React", "GSAP"],
    featured: false,
    description:
      "Architectural firm showcase with real-time 3D building walkthroughs, sunlight simulation, and material configuration for client presentations.",
    accentColor: "#6c757d",
  },

  /* ═══════════════════════════════════════
     SaaS & TECHNOLOGY  (6 projects)
     ═══════════════════════════════════════ */
  {
    id: "saas-1",
    slug: "flowdesk-crm",
    title: "Flowdesk",
    client: "Flowdesk Inc.",
    year: 2025,
    category: "SaaS & Technology",
    thumbnail: "/images/projects/portfolio/flowdesk-crm.webp",
    tags: ["Next.js", "TypeScript", "Supabase", "Stripe"],
    featured: false,
    description:
      "Modern CRM platform with pipeline visualization, AI-powered lead scoring, automated email sequences, and real-time analytics dashboard.",
    accentColor: "#4361ee",
  },
  {
    id: "saas-2",
    slug: "cipher-security",
    title: "Cipher",
    client: "Cipher Cybersecurity",
    year: 2025,
    category: "SaaS & Technology",
    thumbnail: "/images/projects/portfolio/cipher-security.webp",
    tags: ["React", "Node.js", "WebSocket", "D3.js"],
    featured: false,
    description:
      "Cybersecurity monitoring dashboard with real-time threat visualization, attack map, and automated incident response workflows.",
    accentColor: "#00f5d4",
  },
  {
    id: "saas-3",
    slug: "syncboard-pm",
    title: "Syncboard",
    client: "Syncboard Labs",
    year: 2026,
    category: "SaaS & Technology",
    thumbnail: "/images/projects/portfolio/syncboard-pm.webp",
    tags: ["Next.js", "TypeScript", "Real-time", "GSAP"],
    featured: false,
    description:
      "Collaborative project management tool with real-time Kanban boards, Gantt charts, time tracking, and AI-generated task breakdowns.",
    accentColor: "#7209b7",
  },
  {
    id: "saas-4",
    slug: "voxel-analytics",
    title: "Voxel Analytics",
    client: "Voxel Data",
    year: 2025,
    category: "SaaS & Technology",
    thumbnail: "/images/projects/portfolio/voxel-analytics.webp",
    tags: ["React", "D3.js", "WebGL", "TypeScript"],
    featured: false,
    description:
      "Business intelligence platform with 3D data visualization, custom report builder, and predictive analytics powered by machine learning.",
    accentColor: "#3a86ff",
  },
  {
    id: "saas-5",
    slug: "pulse-devops",
    title: "Pulse DevOps",
    client: "Pulse Systems",
    year: 2026,
    category: "SaaS & Technology",
    thumbnail: "/images/projects/portfolio/pulse-devops.webp",
    tags: ["Next.js", "Go", "Docker", "WebSocket"],
    featured: false,
    description:
      "DevOps monitoring and deployment platform with CI/CD visualization, container orchestration dashboard, and uptime analytics.",
    accentColor: "#06d6a0",
  },
  {
    id: "saas-6",
    slug: "echoai-assistant",
    title: "Echo AI",
    client: "Echo Technologies",
    year: 2026,
    category: "SaaS & Technology",
    thumbnail: "/images/projects/portfolio/echoai-assistant.webp",
    tags: ["Next.js", "OpenAI", "TypeScript", "Supabase"],
    featured: false,
    description:
      "AI assistant platform with conversational UI, knowledge base integration, multi-language support, and enterprise-grade security.",
    accentColor: "#8338ec",
  },

  /* ═══════════════════════════════════════
     CORPORATE & BUSINESS  (6 projects)
     ═══════════════════════════════════════ */
  {
    id: "corp-1",
    slug: "meridian-capital",
    title: "Meridian Capital",
    client: "Meridian Capital Group",
    year: 2025,
    category: "Corporate & Business",
    thumbnail: "/images/projects/portfolio/meridian-capital.webp",
    tags: ["Next.js", "GSAP", "TypeScript", "Sanity CMS"],
    featured: false,
    description:
      "Investment firm website with animated portfolio performance charts, team profiles, and a gated investor portal with document management.",
    accentColor: "#1a535c",
  },
  {
    id: "corp-2",
    slug: "quantum-consulting",
    title: "Quantum Consulting",
    client: "Quantum Advisory",
    year: 2025,
    category: "Corporate & Business",
    thumbnail: "/images/projects/portfolio/quantum-consulting.webp",
    tags: ["Next.js", "Framer Motion", "CMS", "TypeScript"],
    featured: false,
    description:
      "Management consulting firm with interactive case study presentations, dynamic team org chart, and client engagement tracking.",
    accentColor: "#2b2d42",
  },
  {
    id: "corp-3",
    slug: "zenith-law",
    title: "Zenith Law",
    client: "Zenith Legal Partners",
    year: 2026,
    category: "Corporate & Business",
    thumbnail: "/images/projects/portfolio/zenith-law.webp",
    tags: ["Next.js", "Supabase", "GSAP", "TypeScript"],
    featured: false,
    description:
      "International law firm website with practice area deep-dives, attorney profiles, case result tracker, and client portal integration.",
    accentColor: "#283618",
  },
  {
    id: "corp-4",
    slug: "bridge-ventures",
    title: "Bridge Ventures",
    client: "Bridge VC",
    year: 2025,
    category: "Corporate & Business",
    thumbnail: "/images/projects/portfolio/bridge-ventures.webp",
    tags: ["React", "GSAP", "D3.js", "Next.js"],
    featured: false,
    description:
      "Venture capital portfolio showcase with interactive fund performance visualizations, startup profiles, and LP reporting dashboard.",
    accentColor: "#457b9d",
  },
  {
    id: "corp-5",
    slug: "atlas-logistics",
    title: "Atlas Logistics",
    client: "Atlas Global Freight",
    year: 2026,
    category: "Corporate & Business",
    thumbnail: "/images/projects/portfolio/atlas-logistics.webp",
    tags: ["Next.js", "Mapbox", "TypeScript", "Node.js"],
    featured: false,
    description:
      "Global logistics company with real-time shipment tracking map, fleet management dashboard, and automated quote calculator.",
    accentColor: "#e76f51",
  },
  {
    id: "corp-6",
    slug: "apex-energy",
    title: "Apex Energy",
    client: "Apex Renewables",
    year: 2025,
    category: "Corporate & Business",
    thumbnail: "/images/projects/portfolio/apex-energy.webp",
    tags: ["Next.js", "Three.js", "D3.js", "TypeScript"],
    featured: false,
    description:
      "Renewable energy company with interactive solar farm 3D viewer, real-time energy production dashboard, and carbon offset calculator.",
    accentColor: "#ffb703",
  },

  /* ═══════════════════════════════════════
     TOURISM & HOSPITALITY  (6 projects)
     ═══════════════════════════════════════ */
  {
    id: "tour-1",
    slug: "aurora-resorts",
    title: "Aurora Resorts",
    client: "Aurora Collection",
    year: 2025,
    category: "Tourism & Hospitality",
    thumbnail: "/images/projects/portfolio/aurora-resorts.webp",
    tags: ["Next.js", "Three.js", "GSAP", "Booking API"],
    featured: false,
    description:
      "Luxury resort chain with virtual room tours in 3D, Northern Lights forecast integration, and a seamless multi-property booking system.",
    accentColor: "#48bfe3",
  },
  {
    id: "tour-2",
    slug: "wanderlust-trails",
    title: "Wanderlust Trails",
    client: "Wanderlust Adventure Co.",
    year: 2025,
    category: "Tourism & Hospitality",
    thumbnail: "/images/projects/portfolio/wanderlust-trails.webp",
    tags: ["Next.js", "Mapbox", "GSAP", "Stripe"],
    featured: false,
    description:
      "Adventure travel platform with interactive trail maps, difficulty ratings, gear checklists, and group booking with split payments.",
    accentColor: "#386641",
  },
  {
    id: "tour-3",
    slug: "sakura-ryokan",
    title: "Sakura Ryokan",
    client: "Sakura Hospitality Group",
    year: 2026,
    category: "Tourism & Hospitality",
    thumbnail: "/images/projects/portfolio/sakura-ryokan.webp",
    tags: ["Next.js", "GSAP", "TypeScript", "Sanity CMS"],
    featured: false,
    description:
      "Traditional Japanese inn experience online — seasonal visual themes, onsen availability calendar, kaiseki menu preview, and cultural experience booking.",
    accentColor: "#ffafcc",
  },
  {
    id: "tour-4",
    slug: "compass-cruises",
    title: "Compass Cruises",
    client: "Compass Maritime",
    year: 2025,
    category: "Tourism & Hospitality",
    thumbnail: "/images/projects/portfolio/compass-cruises.webp",
    tags: ["Three.js", "Next.js", "WebGL", "Stripe"],
    featured: false,
    description:
      "Cruise line booking platform with 3D ship exploration, deck-by-deck virtual tours, excursion planning, and cabin comparison tool.",
    accentColor: "#0096c7",
  },
  {
    id: "tour-5",
    slug: "alpine-lodges",
    title: "Alpine Lodges",
    client: "Alpine Collection",
    year: 2026,
    category: "Tourism & Hospitality",
    thumbnail: "/images/projects/portfolio/alpine-lodges.webp",
    tags: ["Next.js", "GSAP", "Framer Motion", "Booking API"],
    featured: false,
    description:
      "Swiss mountain lodge network with weather-reactive hero visuals, ski trail maps, availability calendars, and seasonal pricing engine.",
    accentColor: "#a8dadc",
  },
  {
    id: "tour-6",
    slug: "ember-safari",
    title: "Ember Safari",
    client: "Ember Expeditions",
    year: 2025,
    category: "Tourism & Hospitality",
    thumbnail: "/images/projects/portfolio/ember-safari.webp",
    tags: ["Next.js", "Three.js", "GSAP", "Stripe"],
    featured: false,
    description:
      "African safari booking platform with immersive 3D wildlife encounters, camp comparison, guided tour scheduling, and wildlife photography gallery.",
    accentColor: "#bc6c25",
  },

  /* ═══════════════════════════════════════
     HEALTHCARE & WELLNESS  (5 projects)
     ═══════════════════════════════════════ */
  {
    id: "health-1",
    slug: "vitalis-clinic",
    title: "Vitalis Clinic",
    client: "Vitalis Medical Group",
    year: 2025,
    category: "Healthcare & Wellness",
    thumbnail: "/images/projects/portfolio/vitalis-clinic.webp",
    tags: ["Next.js", "Supabase", "TypeScript", "HIPAA"],
    featured: false,
    description:
      "Private medical clinic with online appointment scheduling, patient portal, telemedicine integration, and HIPAA-compliant data handling.",
    accentColor: "#219ebc",
  },
  {
    id: "health-2",
    slug: "serenity-wellness",
    title: "Serenity Wellness",
    client: "Serenity Spa & Wellness",
    year: 2026,
    category: "Healthcare & Wellness",
    thumbnail: "/images/projects/portfolio/serenity-wellness.webp",
    tags: ["Next.js", "GSAP", "Framer Motion", "Stripe"],
    featured: false,
    description:
      "Luxury wellness center with treatment builder, therapist matching, membership management, and ambient sound-reactive UI design.",
    accentColor: "#b5838d",
  },
  {
    id: "health-3",
    slug: "mindflow-therapy",
    title: "Mindflow",
    client: "Mindflow Therapy",
    year: 2025,
    category: "Healthcare & Wellness",
    thumbnail: "/images/projects/portfolio/mindflow-therapy.webp",
    tags: ["React", "TypeScript", "WebRTC", "Supabase"],
    featured: false,
    description:
      "Mental health platform with therapist matching, video session booking, mood tracking journal, and progress visualization dashboard.",
    accentColor: "#6d6875",
  },
  {
    id: "health-4",
    slug: "kinetic-physio",
    title: "Kinetic Physio",
    client: "Kinetic Sports Medicine",
    year: 2026,
    category: "Healthcare & Wellness",
    thumbnail: "/images/projects/portfolio/kinetic-physio.webp",
    tags: ["Next.js", "Three.js", "GSAP", "TypeScript"],
    featured: false,
    description:
      "Sports physiotherapy clinic with 3D anatomy viewer, exercise program builder, recovery tracking, and injury prevention education modules.",
    accentColor: "#e63946",
  },
  {
    id: "health-5",
    slug: "bloom-fertility",
    title: "Bloom Fertility",
    client: "Bloom Reproductive Health",
    year: 2025,
    category: "Healthcare & Wellness",
    thumbnail: "/images/projects/portfolio/bloom-fertility.webp",
    tags: ["Next.js", "Supabase", "TypeScript", "Stripe"],
    featured: false,
    description:
      "Fertility clinic platform with treatment timeline visualization, cycle tracking, consultation booking, and educational resource library.",
    accentColor: "#f4a261",
  },

  /* ═══════════════════════════════════════
     REAL ESTATE  (5 projects)
     ═══════════════════════════════════════ */
  {
    id: "re-1",
    slug: "skyline-properties",
    title: "Skyline Properties",
    client: "Skyline Development",
    year: 2025,
    category: "Real Estate",
    thumbnail: "/images/projects/portfolio/skyline-properties.webp",
    tags: ["Three.js", "Next.js", "Mapbox", "GSAP"],
    featured: false,
    description:
      "Premium real estate platform with 3D floor plan walkthroughs, neighborhood insights map, mortgage calculator, and virtual staging tool.",
    accentColor: "#264653",
  },
  {
    id: "re-2",
    slug: "haven-homes",
    title: "Haven Homes",
    client: "Haven Residential",
    year: 2026,
    category: "Real Estate",
    thumbnail: "/images/projects/portfolio/haven-homes.webp",
    tags: ["Next.js", "Three.js", "WebGL", "Supabase"],
    featured: false,
    description:
      "Residential development showcase with interactive site plans, sunlight simulation throughout the day, and unit comparison tool.",
    accentColor: "#2a9d8f",
  },
  {
    id: "re-3",
    slug: "pinnacle-towers",
    title: "Pinnacle Towers",
    client: "Pinnacle Commercial",
    year: 2025,
    category: "Real Estate",
    thumbnail: "/images/projects/portfolio/pinnacle-towers.webp",
    tags: ["Three.js", "Blender", "GSAP", "Next.js"],
    featured: false,
    description:
      "Commercial real estate with 3D building explorer, available floor plans, tenant directory, and lease inquiry system.",
    accentColor: "#6c757d",
  },
  {
    id: "re-4",
    slug: "coastal-living",
    title: "Coastal Living",
    client: "Coastal Developments",
    year: 2026,
    category: "Real Estate",
    thumbnail: "/images/projects/portfolio/coastal-living.webp",
    tags: ["Next.js", "GSAP", "Framer Motion", "Mapbox"],
    featured: false,
    description:
      "Beachfront property showcase with drone-captured 360° views, tide-reactive hero animations, and lifestyle area exploration.",
    accentColor: "#0077b6",
  },
  {
    id: "re-5",
    slug: "urban-nest",
    title: "Urban Nest",
    client: "Urban Nest Properties",
    year: 2025,
    category: "Real Estate",
    thumbnail: "/images/projects/portfolio/urban-nest.webp",
    tags: ["Next.js", "React", "TypeScript", "Supabase"],
    featured: false,
    description:
      "Urban co-living platform with room availability checker, community events calendar, virtual tours, and roommate matching system.",
    accentColor: "#84a98c",
  },

  /* ═══════════════════════════════════════
     FASHION & LUXURY  (5 projects)
     ═══════════════════════════════════════ */
  {
    id: "fash-1",
    slug: "maison-noir",
    title: "Maison Noir",
    client: "Maison Noir Paris",
    year: 2025,
    category: "Fashion & Luxury",
    thumbnail: "/images/projects/portfolio/maison-noir.webp",
    tags: ["Next.js", "GSAP", "WebGL", "Shopify"],
    featured: false,
    description:
      "Parisian haute couture house with runway video experiences, collection lookbooks with parallax storytelling, and exclusive pre-order system.",
    accentColor: "#1d1d1d",
  },
  {
    id: "fash-2",
    slug: "esse-jewelry",
    title: "Essé Jewelry",
    client: "Essé Fine Jewelry",
    year: 2026,
    category: "Fashion & Luxury",
    thumbnail: "/images/projects/portfolio/esse-jewelry.webp",
    tags: ["Three.js", "Next.js", "GSAP", "Stripe"],
    featured: false,
    description:
      "Fine jewelry brand with 3D ring configurator, gemstone education section, virtual try-on, and bespoke consultation scheduling.",
    accentColor: "#cdb4db",
  },
  {
    id: "fash-3",
    slug: "atelier-blanc",
    title: "Atelier Blanc",
    client: "Atelier Blanc Milan",
    year: 2025,
    category: "Fashion & Luxury",
    thumbnail: "/images/projects/portfolio/atelier-blanc.webp",
    tags: ["Next.js", "Framer Motion", "GSAP", "Shopify"],
    featured: false,
    description:
      "Italian fashion atelier with seasonal collection showcases, fabric detail zoom, made-to-measure form, and fashion week event calendar.",
    accentColor: "#f5ebe0",
  },
  {
    id: "fash-4",
    slug: "vanguard-menswear",
    title: "Vanguard",
    client: "Vanguard Menswear",
    year: 2026,
    category: "Fashion & Luxury",
    thumbnail: "/images/projects/portfolio/vanguard-menswear.webp",
    tags: ["Next.js", "GSAP", "TypeScript", "Shopify"],
    featured: false,
    description:
      "Premium menswear brand with style guide AI, wardrobe builder, tailoring appointment system, and editorial photo stories.",
    accentColor: "#495057",
  },
  {
    id: "fash-5",
    slug: "soleil-eyewear",
    title: "Soleil Eyewear",
    client: "Soleil Optics",
    year: 2025,
    category: "Fashion & Luxury",
    thumbnail: "/images/projects/portfolio/soleil-eyewear.webp",
    tags: ["Three.js", "React", "AR.js", "Shopify"],
    featured: false,
    description:
      "Luxury eyewear brand with AR virtual try-on, face-shape analysis, lens customization, and store locator with appointment booking.",
    accentColor: "#e9c46a",
  },

  /* ═══════════════════════════════════════
     FOOD & RESTAURANT  (5 projects)
     ═══════════════════════════════════════ */
  {
    id: "food-1",
    slug: "ember-steakhouse",
    title: "Ember & Oak",
    client: "Ember Steakhouse NYC",
    year: 2025,
    category: "Food & Restaurant",
    thumbnail: "/images/projects/portfolio/ember-steakhouse.webp",
    tags: ["Next.js", "GSAP", "Framer Motion", "TypeScript"],
    featured: false,
    description:
      "New York steakhouse with cinematic food photography, tasting menu explorer, sommelier-curated wine pairings, and real-time reservation system.",
    accentColor: "#9c6644",
  },
  {
    id: "food-2",
    slug: "sakana-omakase",
    title: "Sakana Omakase",
    client: "Sakana Tokyo",
    year: 2026,
    category: "Food & Restaurant",
    thumbnail: "/images/projects/portfolio/sakana-omakase.webp",
    tags: ["Next.js", "GSAP", "TypeScript", "Sanity CMS"],
    featured: false,
    description:
      "Michelin-starred omakase restaurant with seasonal ingredient calendar, chef's journey story, counter seat booking, and sake pairing guide.",
    accentColor: "#d62828",
  },
  {
    id: "food-3",
    slug: "verde-kitchen",
    title: "Verde Kitchen",
    client: "Verde Farm-to-Table",
    year: 2025,
    category: "Food & Restaurant",
    thumbnail: "/images/projects/portfolio/verde-kitchen.webp",
    tags: ["Next.js", "Supabase", "GSAP", "Stripe"],
    featured: false,
    description:
      "Farm-to-table restaurant chain with rotating seasonal menus, local farm partner profiles, meal kit delivery, and cooking class booking.",
    accentColor: "#606c38",
  },
  {
    id: "food-4",
    slug: "crust-bakery",
    title: "Crust & Crumb",
    client: "Crust Artisan Bakery",
    year: 2026,
    category: "Food & Restaurant",
    thumbnail: "/images/projects/portfolio/crust-bakery.webp",
    tags: ["Next.js", "Framer Motion", "Shopify", "TypeScript"],
    featured: false,
    description:
      "Artisanal bakery with daily fresh-baked menu, custom cake designer tool, subscription bread box, and baking workshop calendar.",
    accentColor: "#dda15e",
  },
  {
    id: "food-5",
    slug: "noma-cocktails",
    title: "Noma Cocktails",
    client: "Noma Bar & Lounge",
    year: 2025,
    category: "Food & Restaurant",
    thumbnail: "/images/projects/portfolio/noma-cocktails.webp",
    tags: ["Next.js", "GSAP", "Three.js", "TypeScript"],
    featured: false,
    description:
      "Craft cocktail bar with interactive drink explorer, ingredient story animations, mixology masterclass booking, and private event planning.",
    accentColor: "#5e548e",
  },

  /* ═══════════════════════════════════════
     CREATIVE & PORTFOLIO  (5 projects)
     ═══════════════════════════════════════ */
  {
    id: "cre-1",
    slug: "parallax-studio",
    title: "Parallax Studio",
    client: "Parallax Creative Agency",
    year: 2025,
    category: "Creative & Portfolio",
    thumbnail: "/images/projects/portfolio/parallax-studio.webp",
    tags: ["Three.js", "GSAP", "Next.js", "WebGL"],
    featured: false,
    description:
      "Award-winning creative agency portfolio with project showcases transitioning through 3D space, interactive case studies, and immersive team stories.",
    accentColor: "#ff006e",
  },
  {
    id: "cre-2",
    slug: "mono-type",
    title: "Mono Type",
    client: "Mono Type Foundry",
    year: 2026,
    category: "Creative & Portfolio",
    thumbnail: "/images/projects/portfolio/mono-type.webp",
    tags: ["Next.js", "Canvas API", "GSAP", "TypeScript"],
    featured: false,
    description:
      "Digital type foundry with interactive font specimens, variable font playground, license management, and custom type request system.",
    accentColor: "#212529",
  },
  {
    id: "cre-3",
    slug: "frame-motion",
    title: "Frame & Motion",
    client: "Frame Motion Pictures",
    year: 2025,
    category: "Creative & Portfolio",
    thumbnail: "/images/projects/portfolio/frame-motion.webp",
    tags: ["Next.js", "GSAP", "Three.js", "Framer Motion"],
    featured: false,
    description:
      "Film production company with cinematic video backgrounds, project reel browser, crew directory, and production inquiry funnel.",
    accentColor: "#370617",
  },
  {
    id: "cre-4",
    slug: "pixel-forge",
    title: "Pixel Forge",
    client: "Pixel Forge Games",
    year: 2026,
    category: "Creative & Portfolio",
    thumbnail: "/images/projects/portfolio/pixel-forge.webp",
    tags: ["Three.js", "R3F", "WebGL", "Next.js"],
    featured: false,
    description:
      "Indie game studio website with playable browser demos, development blog with embedded builds, community forum, and merch store.",
    accentColor: "#7b2cbf",
  },
  {
    id: "cre-5",
    slug: "sonance-music",
    title: "Sonance",
    client: "Sonance Music Label",
    year: 2025,
    category: "Creative & Portfolio",
    thumbnail: "/images/projects/portfolio/sonance-music.webp",
    tags: ["Next.js", "Web Audio API", "GSAP", "TypeScript"],
    featured: false,
    description:
      "Independent music label with audio-reactive visual identity, artist pages with embedded players, release calendar, and event ticket sales.",
    accentColor: "#fb5607",
  },
];
